baseurl = "https://potatofrom.space/" # Controls base URL
copyright = "Kevin Liu"
languageCode = "en-US" # Controls site language
paginate = 11 # Number of posts to show before paginating
theme = "terminal" # Set default theme

[outputs]
home = ["HTML", "RSS"]

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 6
  # set theme to full screen width
  fullWidthTheme = false
  # center theme with default width
  centerTheme = true

[languages]
  [languages.en]
    title = "Potatoblog"
    subtitle = "Kevin Liu's sporadically-updated webspace"
    keywords = "blog tech copyright"
    copyright = '''
      <div>
        <p>&copy; 2019 Kevin Liu &middot; Licensed under <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a></p>
        <p>Potato Industries provides an SLA of at least one 9 of uptime (90%). If we
        at any time fail to reach this standard, you are entitled to a refund of
        usage costs.</p>
      </div>
    '''
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Potatoblog"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        name = "GitLab"
        identifier = "gitlab"
        url = "https://gitlab.potatofrom.space"
      [[languages.en.menu.main]]
        name = "Mastodon"
        identifier = "mastodon"
        url = "https://fedi.potatofrom.space"
      [[languages.en.menu.main]]
        name = "Matrix"
        identifier = "matrix"
        url = "https://riot.potatofrom.space"
      [[languages.en.menu.main]]
        name = "About"
        identifier = "about"
        url = "/about"