baseurl = "https://kliu.io/" # Controls base URL
languageCode = "en-US" # Controls site language
paginate = 11 # Number of posts to show before paginating
theme = "whiteplain" # Set default theme
googleAnalytics = "G-KKF0HL5TKT"

# disqus configuration
disqusShortname = "kevin-liu"
copyright = '''
  <p>&copy; 2021 Kevin Liu &middot; Licensed under <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a></p>
'''

[outputs]
home = ["HTML", "RSS"]

[params.author]
name = "Kevin Liu"
twitter = "kliu128"
github = "kliu128"
linkedin = "the-kevin-liu"
email = "kevin@kliu.io"
facebook = "kliu128"
avatar = "/images/avatar.jpg"

[languages]
  [languages.en]
    title = "Kevin Liu"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Kevin Liu"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/post"
      [[languages.en.menu.main]]
        identifier = "objects"
        name = "Objects"
        url = "/objects"
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects"