apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: blog
    ref: __CI_ENVIRONMENT_SLUG__
  name: blog
spec:
  replicas: 2
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: blog
        ref: __CI_ENVIRONMENT_SLUG__
    spec:
      containers:
      - image: registry.kliu.io/kevin/potatofrom.space:__VERSION__
        name: blog
      restartPolicy: Always
status: {}